Lab41/pelops

- README.md
- testci/test_sample.py
- transform_img/install.sh
- transform_img/run.sh
- transform_img/transform.py
Fully tested to be working. Transform images to blur, shrink then enlarge, or grayscale.
> Transform img

- transform_img/transform.py
needed to move some of the things around to make multiprocessing happy with pickling the functions..
> multiprocessing of the images..

- experiment_api/experiment.py
- experiment_api/run.sh
Create an experiment api. Still need to put differentiator in timestamp and cleanup comments in code.
> Experiment

- testci/test_chipbase.py
> Add first set of tests for ChipBase

- pelops/datasets/chip.py
- pelops/datasets/featuredataset.py
- pelops/etl/extract_feats_from_chips.py
- pelops/experiment_api/experiment.py
- requirements.txt
- testci/test_featuredataset.py
Adding a child class of ChipDataset that contains image features
> Featuredataset

- pelops/training/utils.py
- testci/test_training_utils.py
Added code to help retrain Resnet50.
> Add Retraining Helpers 

- pelops/training/utils.py
- testci/test_training_utils.py
This method writes the Class to Index map out as a JSON file so that it
can be reused later.
> Add `KerasDirectory.write_map()` method

- pelops/datasets/chip.py
- pelops/datasets/dgcars.py
- testci/test_dgcars.py
Add a `ChipDataset()` daughter class for DG Cars. Includes tests.
Since this is a "showroom" dataset, `car_id`, `cam_id`, and `time` are all `None`. The `chip_id` is the full path to the file, as we have done with other classes.
> Add `DGCarsDataset()`

- pelops/datasets/chipper.py
Initial Commit of code that reads a video file and extracts chips in two different ways
> Initial Commit of Chipping Code

- pelops/analysis/analysis.py
- pelops/analysis/test_analysis.py
- pelops/datasets/compcar.py
- testci/test_dgcars.py
- testci/test_training_utils.py
This is sort of trivial but I figured it's a way to get familiar first.
> fix some spelling typos

- pelops/datasets/chipper.py
- requirements.txt
- testci/test_chipper.py
This uses the name of the video, the offset, and the frame number to calculate the local timestamp.
> Add timestamp to Frames and ExtractedChip

- pelops/datasets/chipper.py
- pelops/etl/extract_feats_from_chips.py
- pelops/utils.py
Checking in the feature producer code
> Initial Commit of Feature Producer

- circle.yml
- pelops/features/resnet50.py
- requirements.txt
- testci/test_hog_feature.py
- testci/test_keras_model_feature.py
- testci/test_resnet50_feature.py
Adding additional tests for #50.
> Add tests for HOGFeatureProducer

- pelops/features/feature_producer.py
- testci/test_featureproducer.py
I found a bug in `FeatureProducer()` while trying to extract HOG features. This fixes the bug and adds tests to catch it in the future.
> `FeatureProducer()` bug fix

- testci/test_keras_load_model.py
didnt test locally when circleci environment variable changed.
> CIRCLECI 'false'

- circle.yml
The `menpo` library is unused.
> Remove `menpo` from installation

- testci/test_featuredataset.py
> Use `pytest.tmpdir` to assign filenames

- pelops/datasets/veri.py
- testci/test_veri.py
> Add color and vehicle type to VeRI chips

- pelops/analysis/siamese.ipynb
resnet50 basic siamese network to start with. (probably need to bolt something more substantial on the top of this thing..)
> adding initial siamese notebook

- docker/Dockerfile.images2vecs
differences start after line 27 now. (should make layer caching happier)
> making the 2 docker files more similar.

- pelops/features/hog.py
- testci/test_hog_feature.py
> Add color histograms to HOG extractor

- pelops/experiment_api/experiment.py
- pelops/utils.py
Modify the Experiment API to allow for excluding certain keys. Also create a deterministic helper function that splits based on the hash of the key
> Veri split

- docker/Dockerfile.pelops
- docker/pelops_start.sh
This adds the first draft of a container to run code using the most recent version of the project. The goal is to allow some basic notebooks to run on the SA data to do:
- Chipping
- Feature extraction (HOG and ResNet)
- Matching
> Add first draft of Docker container

- pelops/analysis/ScoreChips.ipynb
This notebook from Yonas optimizes the chipper parameters using a set of labeled data.
> Chipper parameter optimizer

- pelops/analysis/CMC_Confidence.ipynb
- pelops/datasets/slice.py
- testci/test_slice.py
chip.Chip.time as epoch instead of iso
> SLiCE Dataset bug fix

- pelops/features/resnet50.py
Only apply resizing and interpolation when the incoming image does not match the desired dimensions.
> Mod to ResNet50 Feature Producer

- pelops/datasets/slice.py
- testci/test_slice.py
Adding support for the higher res slice data.
> Add support for High Res Slice data

- docker/Dockerfile.test
> Update Docker test container

- docker/Dockerfile.base
This fixes #101.
Also pin all versions added, and update `pip` so it will stop
complaining about being an old version.
> Add `hdfs3` to base container

- docs/chips_to_features.md
Fixed a mistake in the current instructions.
> Update instructions for using the ranker container

- etl/makeFeaturesYOURMODEL.py
Appears Jonathan has already submitted a pull request for this.  At any rate, there is another. -sk
> Pull req 105

- docs/chips_to_features.md
Minor correction to docker run line under bullet 3
> [docs] - Update to BYOM instructions

- etl/makeFeaturesYOURMODEL.py
I was able to verify that the shape of the resnet weights within the siamese subtract net is identical to the default resnet weights shape.  Seems that a direct application of the weights from siamese to fresh resnet is appropriate.
No adaptation to external interfaces needed to support i2v using siamese.
> [BYOM] Accept resnet embedded within siamese subtract net

- docker/Dockerfile.csv2json
- docs/chips_to_features.md
- etl/convertCsvToJson.py
- makefile
- pelops/utils.py
As per request from Jonathan, added a new docker file and associated exec script for running the csv to json conversion script for i2v feature vectors.  Documentation updated as well.
> [Docker] New docker container and script for converting CSV to JSON

- pelops/utils.py
Added `pelops.utils.prep_for_siamese` which produces a siamese docker compatible json vector file from an arbitrary number of i2v produced feature vector csv files.
> [i2v -> Siamese] Convert feature vector csv to json
